import { execFileSync } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'

const DEFAULT_MODEL = process.env.REVIEW_MODEL || 'openai/gpt-4o-mini'
const isCI = process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true'
const githubToken = process.env.GITHUB_TOKEN
const repo = process.env.GITHUB_REPOSITORY
const pullNumber = process.env.PR_NUMBER
const rubricPath = path.resolve(process.cwd(), 'review-guides', 'react-review.md')

function runGit(args) {
  return execFileSync('git', args, {
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  }).trim()
}

function safeGit(args) {
  try {
    return runGit(args)
  } catch {
    return ''
  }
}

function getDiffTarget() {
  const base = process.env.REVIEW_BASE_SHA
  const head = process.env.REVIEW_HEAD_SHA

  if (base && head) {
    return { range: `${base}...${head}`, mode: 'range' }
  }

  const mergeBase = safeGit(['merge-base', 'HEAD', 'origin/main'])
  if (mergeBase) {
    return { range: `${mergeBase}...HEAD`, mode: 'range' }
  }

  return { range: 'HEAD', mode: 'working-tree' }
}

function getChangedFiles(range, mode) {
  const args =
    mode === 'range'
      ? ['diff', '--name-only', range, '--', '.', ':(exclude)dist', ':(exclude)node_modules']
      : ['diff', '--name-only', 'HEAD', '--', '.', ':(exclude)dist', ':(exclude)node_modules']

  const output = safeGit(args)
  return output ? output.split('\n').filter(Boolean) : []
}

function getDiff(range, mode) {
  const args =
    mode === 'range'
      ? ['diff', '--unified=3', range, '--', '.', ':(exclude)dist', ':(exclude)node_modules']
      : ['diff', '--unified=3', 'HEAD', '--', '.', ':(exclude)dist', ':(exclude)node_modules']

  return safeGit(args)
}

function writeSummary(markdown) {
  const summaryPath = process.env.GITHUB_STEP_SUMMARY
  if (summaryPath) {
    fs.appendFileSync(summaryPath, `${markdown}\n`)
  }
}

function parseReviewJson(rawContent) {
  const trimmed = rawContent.trim()
  const fenced = trimmed.match(/^```(?:json)?\s*([\s\S]*?)\s*```$/i)
  const candidate = fenced ? fenced[1].trim() : trimmed
  return JSON.parse(candidate)
}

function loadRubric() {
  if (!fs.existsSync(rubricPath)) {
    return ''
  }

  return fs.readFileSync(rubricPath, 'utf8').trim()
}

function compactFindings(findings) {
  if (!Array.isArray(findings) || findings.length === 0) {
    return '- No high-risk issues were identified.'
  }

  return findings
    .map((finding) => {
      const severity = finding.severity ? `[${finding.severity}]` : '[info]'
      const location = finding.file ? ` ${finding.file}` : ''
      const issue = finding.issue || finding.summary || 'Issue not specified'
      const suggestion = finding.suggestion ? ` Suggestion: ${finding.suggestion}` : ''
      return `- ${severity}${location}: ${issue}${suggestion}`
    })
    .join('\n')
}

function buildCommentBody(review, shouldFail) {
  const findings = Array.isArray(review.findings) ? review.findings : []
  const bestPractices = Array.isArray(review.best_practices) ? review.best_practices : []
  const missingTests = Array.isArray(review.missing_tests) ? review.missing_tests : []

  return [
    '<!-- ai-code-review -->',
    '## AI Code Review',
    '',
    `Verdict: **${review.verdict || 'needs_changes'}**${shouldFail ? ' (blocking)' : ''}`,
    '',
    review.summary ? review.summary : 'No summary provided.',
    '',
    '### Findings',
    compactFindings(findings),
    '',
    '### Best Practices',
    bestPractices.length ? bestPractices.map((item) => `- ${item}`).join('\n') : '- No additional notes.',
    '',
    '### Missing Tests',
    missingTests.length ? missingTests.map((item) => `- ${item}`).join('\n') : '- No test gaps were identified.',
    '',
    '_Generated by GitHub Models in GitHub Actions._',
  ].join('\n')
}

async function upsertPullRequestComment(markdown) {
  if (!githubToken || !repo || !pullNumber) {
    return
  }

  const [owner, repoName] = repo.split('/')
  if (!owner || !repoName) {
    throw new Error(`Invalid GITHUB_REPOSITORY value: ${repo}`)
  }

  const listResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repoName}/issues/${pullNumber}/comments?per_page=100`,
    {
      headers: {
        Authorization: `Bearer ${githubToken}`,
        Accept: 'application/vnd.github+json',
        'X-GitHub-Api-Version': '2026-03-10',
      },
    },
  )

  if (!listResponse.ok) {
    const errorText = await listResponse.text()
    throw new Error(`Failed to list PR comments: ${listResponse.status} ${errorText}`)
  }

  const comments = await listResponse.json()
  const existing = Array.isArray(comments)
    ? comments.find(
        (comment) =>
          comment?.body?.includes('<!-- ai-code-review -->') &&
          comment?.user?.login === 'github-actions[bot]',
      )
    : null

  const method = existing ? 'PATCH' : 'POST'
  const endpoint = existing
    ? `https://api.github.com/repos/${owner}/${repoName}/issues/comments/${existing.id}`
    : `https://api.github.com/repos/${owner}/${repoName}/issues/${pullNumber}/comments`

  const response = await fetch(endpoint, {
    method,
    headers: {
      Authorization: `Bearer ${githubToken}`,
      Accept: 'application/vnd.github+json',
      'Content-Type': 'application/json',
      'X-GitHub-Api-Version': '2026-03-10',
    },
    body: JSON.stringify({ body: markdown }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    throw new Error(`Failed to write PR comment: ${response.status} ${errorText}`)
  }
}

async function main() {
  if (!githubToken) {
    const message = 'GITHUB_TOKEN is not set. GitHub Models needs it to run AI code review.'
    console.log(message)
    if (isCI) {
      process.exit(1)
    }
    return
  }

  const { range, mode } = getDiffTarget()
  const files = getChangedFiles(range, mode)
  const diff = getDiff(range, mode)

  if (!files.length) {
    const message = 'No changed source files found to review.'
    console.log(message)
    writeSummary(`## AI Review\n\n${message}\n`)
    return
  }

  const diffLimit = 40000
  const trimmedDiff =
    diff.length > diffLimit
      ? `${diff.slice(0, diffLimit)}\n\n[Diff truncated because it exceeded ${diffLimit} characters.]`
      : diff
  const rubric = loadRubric()

  const prompt = [
    'Review the following pull request diff for a React + TypeScript + Vite portfolio app.',
    'Focus on correctness, security, regressions, accessibility, maintainability, and best practices.',
    'Be strict about real risk, but avoid generic advice.',
    rubric ? 'Use this review rubric as the primary checklist:' : '',
    rubric,
    'Return JSON with this shape:',
    '{',
    '  "verdict": "approve" | "needs_changes" | "block",',
    '  "summary": "short paragraph",',
    '  "findings": [',
    '    {',
    '      "severity": "high" | "medium" | "low",',
    '      "file": "path or empty string",',
    '      "issue": "what is risky or weak",',
    '      "suggestion": "how to improve it"',
    '    }',
    '  ],',
    '  "best_practices": ["..."],',
    '  "missing_tests": ["..."]',
    '}',
    'Return valid JSON only.',
    '',
    `Changed files:\n${files.map((file) => `- ${file}`).join('\n')}`,
    '',
    'Diff:',
    trimmedDiff,
  ].join('\n')

  const response = await fetch('https://models.github.ai/inference/chat/completions', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${githubToken}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
      'X-GitHub-Api-Version': '2022-11-28',
    },
    body: JSON.stringify({
      model: DEFAULT_MODEL,
      temperature: 0.1,
      response_format: { type: 'json_object' },
      messages: [
        {
          role: 'system',
          content:
            'You are a senior software reviewer. Be concise, direct, and specific. Focus on actionable risk and best practices.',
        },
        { role: 'user', content: prompt },
      ],
    }),
  })

  if (!response.ok) {
    const errorText = await response.text()
    console.error(`GitHub Models request failed: ${response.status} ${response.statusText}`)
    console.error(errorText)
    if (response.status === 403) {
      console.error(
        '\nEnable GitHub Models in repo settings: Settings -> Models -> set "Models in this repository" to Enabled.',
      )
    }
    process.exit(1)
  }

  const payload = await response.json()
  const rawContent = payload?.choices?.[0]?.message?.content
  if (!rawContent) {
    console.error('GitHub Models response did not include review content.')
    process.exit(1)
  }

  let review
  try {
    review = parseReviewJson(rawContent)
  } catch (error) {
    console.error('Failed to parse AI review as JSON.')
    console.error(rawContent)
    throw error
  }

  const verdict = review.verdict || 'needs_changes'
  const findings = Array.isArray(review.findings) ? review.findings : []
  const bestPractices = Array.isArray(review.best_practices) ? review.best_practices : []
  const missingTests = Array.isArray(review.missing_tests) ? review.missing_tests : []
  const hasBlockingFinding = findings.some((finding) => finding.severity === 'high')
  const shouldFail = verdict === 'block' || hasBlockingFinding

  const markdown = [
    '## AI Review',
    '',
    `Verdict: **${verdict}**`,
    '',
    review.summary ? review.summary : 'No summary provided.',
    '',
    '### Findings',
    compactFindings(findings),
    '',
    '### Best Practices',
    bestPractices.length ? bestPractices.map((item) => `- ${item}`).join('\n') : '- No additional notes.',
    '',
    '### Missing Tests',
    missingTests.length ? missingTests.map((item) => `- ${item}`).join('\n') : '- No test gaps were identified.',
  ].join('\n')

  console.log(markdown)
  writeSummary(markdown)
  await upsertPullRequestComment(buildCommentBody(review, shouldFail))

  if (shouldFail) {
    process.exit(1)
  }
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
